version: "3"

services:
  backend:
    build: ./backend
    command: node server.js
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/usr/src/app
  fronted:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
